---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-mycrd-k8s-v1alpha1-appscode
  failurePolicy: Fail
  name: mappscode.kb.io
  rules:
  - apiGroups:
    - mycrd.k8s
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - appscodes
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-mycrd-k8s-v1alpha1-appscode
  failurePolicy: Fail
  name: vappscode.kb.io
  rules:
  - apiGroups:
    - mycrd.k8s
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - appscodes
  sideEffects: None
